python/ejercicio17/directores/cine/urls.py
from django.urls import path

from . import views

urlpatterns = [
  path('', views.IndexView.as_view(), name='index'),
  path('<pk>', views.DirectorView.as_view(), name='director'),
  path('unapelicula/<pk>', views.PeliculaView.as_view(), name='pelicula'),
]

python/ejercicio17/directores/directores/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cine.urls')),
]

python/ejercicio17/directores/cine/models.py
from django.db import models

class Director(models.Model):
    nombre = models.CharField(max_length=25)
    apellidos = models.CharField(max_length=50)
    pais = models.CharField(max_length=25)
    edad = models.PositiveIntegerField()

    def __str__(self):
        return self.nombre + " " + self.apellidos + " " + self.pais  + " " + str(self.edad)

class Pelicula(models.Model):
    director = models.ForeignKey('Director', on_delete=models.CASCADE)
    titulo = models.CharField(max_length=25)
    anyo = models.PositiveIntegerField()
    descripcion = models.TextField()

    def __str__(self):
        return self.titulo + " " + str(self.anyo) + " " + self.descripcion 

python/ejercicio17/directores/cine/views.py
# from django.shortcuts import render

from django.views import generic

from .models import Director, Pelicula

class IndexView(generic.ListView):
    template_name = 'cine/cine.html'
    model = Director

class DirectorView(generic.DetailView):
    template_name = 'cine/undirector.html'
    model = Director

class PeliculaView(generic.DetailView):
    template_name = 'cine/unapelicula.html'
    model = Pelicula

python/ejercicio17/directores/cine/templates/cine/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head><title>{% block title %}{% endblock %}</title></head>

<body>
    {% block content %}{% endblock %}
</body>
</html>

python/ejercicio17/directores/cine/templates/cine/cine.html
{% extends "cine/base.html" %}

{% block title %}Cine{% endblock %}


{% block content %}
<h1>Listado de directores</h1>
<table style="border: 1px black solid;">
    {% for director in object_list %}
        <tr>
            <td><a href="/{{director.id}}">{{ director }}</a></td>
        </tr>
    {% endfor %}
</table>
{% endblock %}

python/ejercicio17/directores/cine/templates/cine/unapelicula.html
{% extends "cine/base.html" %}

{% block title %}Una película{% endblock %}

<h1>Información de la película</h1>
{% block content %}
  <p>{{ pelicula.titulo }}</p>
  <p>{{ pelicula.anyo }}</p>
  <p>{{ pelicula.descripcion }}</p>
  <br><hr>
  <a style="color:red" href="/">VOLVER</a>
{% endblock %}


python/ejercicio17/directores/cine/templates/cine/undirector.html
{% extends "cine/base.html" %}

{% block title %}Un Director{% endblock %}


{% block content %}


<p>{{ director.nombre }}</p>
<p>{{ director.apellidos }}</p>
<p>{{ director.pais }}</p>
<p>{{ director.edad }}</p>

<h1>Listado de películas del director</h1>
<table>
    {% for pelicula in director.pelicula_set.all %}
    <tr>
        <td> <a href='/unapelicula/{{pelicula.id}}'>{{ pelicula }}</a></td>
    </tr>
    {% endfor %}
</table>
<br><hr>
<a style="color:red" href="/">VOLVER</a>
{% endblock %}